-- CODIGO ADICIONAL

--Cración de Secuencias
create sequence SECIdPlanPago;
create sequence SECIdUserCargo;
create sequence SECIdPago;
create sequence SECIdPagoCargo;

--Como Iterar sobre las secuencias
SECIdPlanPago.NEXTVAL;
SECIdUserCargo.NEXTVAL;
SECIdPago.NEXTVAL;
SECIdPagoCargo.NEXTVAL;


--1. INSTRUCCIONES DE LA TABLA MONEDA
INSERT INTO MONEDA
VALUES(2,'DOLAR');

SELECT * FROM MONEDA;

--DELETE FROM MONEDA;


--2. INSTRUCCIONES DE LA TABLA PLAN_PAGO
INSERT INTO PLAN_PAGO
VALUES(SECIdPlanPago.NEXTVAL,('2016001'),TO_DATE('2016/01/01', 'YYYY/MM/DD'),5000, 2, 1);

SELECT * FROM PLAN_PAGO;

--DELETE FROM PLAN_PAGO;


--3. INSTRUCCIONES DE LA TABLA CARGO

SELECT * FROM PLAN_PAGO;

--DELETE FROM PLAN_PAGO;

