-- CODIGO ADICIONAL

--Cración de Secuencias
create sequence SECIdPlanPago;
create sequence SECIdUserCargo;
create sequence SECIdPago;
create sequence SECIdPagoCargo;

--Como Iterar sobre las secuencias
SECIdPlanPago.NEXTVAL;
SECIdUserCargo.NEXTVAL;
SECIdPago.NEXTVAL;
SECIdPagoCargo.NEXTVAL;


--1. INSTRUCCIONES DE LA TABLA MONEDA
INSERT INTO MONEDA
VALUES(2,'DOLAR');

SELECT * FROM MONEDA;

--DELETE FROM MONEDA;


--2. INSTRUCCIONES DE LA TABLA PLAN_PAGO
INSERT INTO PLAN_PAGO
VALUES(SECIdPlanPago.NEXTVAL,('2016001'),TO_DATE('2016/01/01', 'YYYY/MM/DD'),5000, 2, 1);

SELECT * FROM PLAN_PAGO;

--DELETE FROM PLAN_PAGO;


--3. INSTRUCCIONES DE LA TABLA CARGO

SELECT * FROM PLAN_PAGO;

--DELETE FROM PLAN_PAGO;

/**************************************************************************************************************************************/

SELECT *
FROM CARGO
WHERE CARNE = '2016001'
ORDER BY MONEDA asc, FECHA_VENCIMIENTO ASC;

SELECT *
FROM CARGO
WHERE CARNE = '2016001'
ORDER BY MONEDA desc, FECHA_VENCIMIENTO ASC;

SELECT *
FROM PAGO;

SELECT * FROM PAGO_CARGO; 
SELECT * FROM PLAN_PAGO;

INSERT INTO PLAN_PAGO
VALUES(SECIdPlanPago.NEXTVAL,'2016001',TO_DATE('2016/01/01', 'YYYY/MM/DD'), 5000, 2, 1);
INSERT INTO PLAN_PAGO
VALUES(SECIdPlanPago.NEXTVAL,'2016001',TO_DATE('2016/01/01', 'YYYY/MM/DD'), 500, 2, 2);

INSERT INTO PAGO
VALUES(SECIdPago.NEXTVAL, '2016001', TO_DATE('2016/01/01', 'YYYY/MM/DD'), 3000, 'Pago 1', 1, 7.73);

INSERT INTO PAGO
VALUES(SECIdPago.NEXTVAL, '2016001', TO_DATE('2016/01/01', 'YYYY/MM/DD'), 200, 'Pago 1', 2, 7.73);

Commit;
--delete from Cargo;
--DELETE FROM PAGO_CARGO;
--delete from Plan_Pago;
--DELETE FROM PAGO;


SELECT PAGO, CARNE, FECHA_APLICACION, MONTO, NULL AS FECHA_VENCIMIENTO, DESCRIPCION
FROM PAGO
UNION
SELECT CARGO, CARNE, FECHA_TRANSACCION, MONTO, FECHA_VENCIMIENTO, DESCRIPCION
FROM CARGO 
ORDER BY CARNE ASC;